app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: 3600000 # 1 hora

spring:
  application:
    name: pensieve
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/postgres?user=postgres
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  address: 127.0.0.1

springdoc:
  swagger-ui:
    path: /swagger-ui.html

